---
title: '[STA 310] data checking'
output: html_document
date: "2023-10-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
```

```{r}
#loading the billionaire data
bill<- read.csv("Bill.csv")

#loading the world bank data
wb<- read.csv("worldbank.csv")

# Loading
country = read.csv("country.csv")
```

```{r}
# Update entries in countries dataset to match with entries in billionaires dataset
country = select(country, c("Country", "GDP", "CPI"))
country$CPI = as.numeric(country$CPI)
country$GDP = as.numeric(gsub('[$,]', '', country$GDP))
country$GDP = country$GDP / 1000000000
country = country %>% add_row(Country = "Taiwan", CPI = 106.52,GDP = 790.7) %>% add_row(Country = "Hong Kong", CPI = 105.60, GDP = 369.2) %>% add_row(Country = "Macau", CPI = 104.86, GDP = 30.12)
country$Country <- country$Country %>%
  str_replace_all("Republic of Ireland","Ireland") %>%
  str_replace_all("Eswatini","Eswatini (Swaziland)") %>%
  str_replace_all("Saint Kitts and Nevis","St. Kitts and Nevis")
```

```{r}
#checking if all the countries are included in the world bank dataset
list_country_wb <- unique(wb$Country.Name)
list_country_bill <- unique(bill$countryOfCitizenship)

for(i in 1:77){
  if((list_country_bill[i] %in% list_country_wb)==FALSE)
    print(list_country_bill[i])
}

# Hongkong = Hong Kong SAR, China
# Russia = Russian Federation
# Czech Republic = Czechia
# South Korea = Korea, Rep.
# Taiwan = 	Taiwan, China
# Egypt = Egypt, Arab Rep.
# Eswatini (Swaziland) = 	Eswatini
# Turkey = Turkiye
# Venezuela = Venezuela, RB
# Guernsey = 
# slovakia = Slovak Republic
# Macau = Macao SAR, China
```

```{r}
#arranging the country's name in world bank equal to billionaire dataset
wb_format<- wb$Country.Name %>%
  str_replace_all("Hong Kong SAR, China","Hong Kong") %>%
  str_replace_all("Russian Federation","Russia") %>%
  str_replace_all("Czechia","Czech Republic") %>%
  str_replace_all("Korea, Rep.","South Korea") %>%
  str_replace_all("Taiwan, China","Taiwan") %>%
  str_replace_all("Egypt, Arab Rep.","Egypt") %>%
  str_replace_all("Eswatini","Eswatini (Swaziland)") %>%
  str_replace_all("Turkiye","Turkey") %>%
  str_replace_all("Venezuela, RB","Venezuela") %>%
  str_replace_all("Slovak Republic","Slovakia") %>%
  str_replace_all("Macao SAR, China","Macau")
```

```{r}
#including the column of formatted country name in the world bank data
wb$newname <- wb_format
```

```{r}
list_country_wb2<- unique(wb$newname)
for(i in 1:77){
  if((list_country_bill[i] %in% list_country_wb2)==FALSE)
    print(list_country_bill[i])
}
```

```{r}
#dropping the countries that does not have top 2639 billionaires 
list_country_bill <- unique(bill$countryOfCitizenship)
wb_count <- filter(wb, wb$newname%in% list_country_bill)

#dropping columns that are not needed
wb_drop <- wb_count %>%
  select(-c(Country.Code,Series.Code, X2021..YR2021., Country.Name))
```


```{r}
#pivoting the data so that each country takes one row
wb_wide <- pivot_wider(wb_drop, 
                       id_cols = newname,
                       names_from =Series.Name, 
                       values_from = X2022..YR2022.)
```

```{r}
merge_data<- left_join(bill, wb_wide,by =c('countryOfCitizenship'='newname'))
```

```{r}
#removing observations including &family in the name
my_data<- merge_data%>%
  filter(str_detect(personName, "& family", negate = TRUE))
```

```{r}


list_country_gdp <- unique(country$Country)
list_country_mydata <- unique(my_data$countryOfCitizenship)

for(i in 1:length(list_country_mydata)){
  if((list_country_mydata[i] %in% list_country_gdp)==FALSE)
    print(list_country_mydata[i])
}


# Update missing values in billionaires dataset using countries datset
for(i in 1:length(my_data$cpi_country)) {
  if (is.na(my_data$cpi_country[i])) {
    my_data$cpi_country[i] = country$CPI[country$Country == my_data$countryOfCitizenship[i]]
  }
  my_data$gdp_country[i] = country$GDP[country$Country == my_data$countryOfCitizenship[i]]
}

my_data$gdp_country = as.numeric(my_data$gdp_country)

# Drop NA entries from countries that don't have CPI data
my_data = my_data %>% drop_na(cpi_country)
```


```{r}
#adding a age group variable

check_over_50 <- function(age) {
  if (any(is.na(age))) {
    return("na")
  } else if(age < 50) {
    return(FALSE)
  } else {
    return(TRUE)
  }
}

my_data$isOver50 = sapply(my_data$age, check_over_50)
my_data = filter(my_data, age != -1)
```

```{r}
# Creating a training and test set
set.seed(1025)
sample <- sample.int(n = nrow(my_data), size = floor(.7*nrow(my_data)), replace = F)
train <- my_data[sample, ]
test  <- my_data[-sample, ]
train = train %>% mutate(TFinalWorth = log(log(train$finalWorth)))
```


```{r}
# train1 = select(train, c("TFinalWorth", "gdp_country", "cpi_country", "Control of Corruption: Estimate", "Control of Corruption: Number of Sources", "Control of Corruption: Percentile Rank", "Government Effectiveness: Percentile Rank", "Political Stability and Absence of Violence/Terrorism: Estimate", "Regulatory Quality: Number of Sources", "Rule of Law: Estimate", "Rule of Law: Number of Sources", "Voice and Accountability: Estimate", "Voice and Accountability: Number of Sources"))

# lm(formula = TFinalWorth ~ gdp_country, data = train1)
# Multiple R-squared:  0.09036,	Adjusted R-squared:  0.05277
# We can use any country-related variable and would still get the same R2 value. We decided to go with gdp_country for simpler analysis. 

# GDP is added with the rest of the variables for a second step-wise test
train2 = select(train, c("isOver50", "TFinalWorth", "industries", "selfMade", "gdp_country", "gender"))

# lm(formula = TFinalWorth ~ isOver50 + selfMade + gdp_country, data = train2)

# Residual standard error: 0.09598 on 1589 degrees of freedom
# Multiple R-squared:  0.01245,	Adjusted R-squared:  0.01058 
# F-statistic: 6.675 on 3 and 1589 DF,  p-value: 0.0001775

full.model2= lm(TFinalWorth~., data = train2)
step.model2 <- step(full.model2)
summary(step.model2)
```

```{r}
### TODO: Run best subsets on main dataset, create mplots with top variables, create pairs plot to check for correlation, check residual plots 
```

```{r}
ggplot(data = train, aes(x = age, y = TFinalWorth)) + geom_point()  + aes(colour = gender) + facet_wrap(~selfMade, ncol = 4)  + stat_smooth(method = lm) + theme(legend.position = "right") + labs(title = "Billionares' Net Worth vs. Age by Self-made Status and Gender", x = "Age", y = "Net Worth (in Millions double logged)")
```

```{r}
best.model = lm(formula = TFinalWorth ~ isOver50 + selfMade + gdp_country, data = train2)
best.model.res = best.model$res
best.model.fit = best.model$fit

par(mfrow=c(2,2))
plot(train2$gdp_country, best.model.res, xlab = "GDP per country", ylab = "Residuals")
plot(best.model.fit, best.model.res, xlab = "Fitted Values", ylab = "Residuals")
plot(train2$selfMade, best.model.res, xlab = "Selfmade", ylab = "Residuals")
plot(train2$isOver50, best.model.res, xlab = "Over 50 Years Old", ylab = "Residuals")
```



